language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda-build
  - panda --notests install WebService::HazIP
  - panda --notests install HTTP::UserAgent

script:
  - PERL6LIB=lib prove -e perl6 -vr t/
sudo: false
